### ISSUE TITLE
Only downloads first 10 images of Imgur album.

### ISSUE THREAD

**Issue by MintGreenIceCream** [W1R3D-Code/RedditRip#1]
Hi, when I download imgur albums, because of the way the site works (it loads the first 10 images and then requires you to click on a prompt to load the rest), it only downloads the first 10 images of the album.

Do you think you are able to fix this issue? Many thanks, your program has been really helpful.

**Comment by FatOrangutan** [comment]
Would like to add my vote to this too. Please take a look into this. Thanks.

**Comment by W1R3D-Code** [comment]
Sorry for never getting back to you, I honestly never thought anyone looked at this :speak_no_evil:
You've probably moved on now, but I'll take a look and try and fix it :bowtie:

**Comment by W1R3D-Code** [comment]
If you have an example that would be useful, imgur has multiple types of album and some load all the images at once e.g. http://imgur.com/a/Dc2k6#0
At least it is right now in Chrome; it could well be dependent on other factors.
